<a href="https://colab.research.google.com/github/mikesenape/Lab-3-/blob/main/Michael_Senape_Stats_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [ ]:
for i in range(100):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


Use i to give the range of 100 and add print(i) to easily print the range

In [ ]:
for i in range(5,8):
    print(i)

5
6
7


use i in the range if number 5-8; it will print the 3 numbers from 5 up to 8

In [ ]:
for i in range(3):
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


insert i in range(3) and add print test number to simulate a serieds of tests; number starting from 0 up to 2

### Functions

In [ ]:
def square(x):
    return x**2

inserted square(x) to be a function used to sqaure x's value

In [ ]:
square(5)

25

x = 5 here and is sqaured

In [ ]:
square(square(2))

16

we can sqaure a number twice putting the original function in ()

In [ ]:
square(square(square(2)))


256

used the square function again here to make the exponent 6

In [ ]:
square(123456)

15241383936

inserted a big number

In [ ]:
square(square(5))

625

In [ ]:
def add_two(x):
    return x+2

created a function to add two to x

In [ ]:
add_two(5)

7

used the function to add 2 to 5

In [ ]:
square(add_two(5))

49

combined both functions to add two to five and then square it

### Logical Branching

In [ ]:
choice = "apple"

gave choice the word apple

In [ ]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


if you chose the word apple then it will print "you chose apples"
inserted else to print you did not choose apples

In [ ]:
choice = "orange"

give choice another word orange

In [ ]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


insert print 'you did not choose apples

In [ ]:
choice = "apple"

In [ ]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


inserted both choices of apples and a elif of orange
insert else to print you did not choose apples or oranges
insert a print of "thank you, shop again!" after your choice

### User Input

In [ ]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): apple


In [ ]:
choice

'apple'

In [ ]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose apples.


in this section we used the virtual market to insert our choice

#### Coins

In [ ]:
import numpy as np

In [ ]:
np.random.random()

0.3086089354492998

In [ ]:
np.random.random() > 0.5

True

used np.random.random to insert a random number
made the rage > 0.5

In [ ]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

inserted flip coin to give us a rabndom number greater than 0.5 heads
if less than it is tails

In [ ]:
flip_coin()

Tails


### Graphics Output

In [ ]:
from IPython.core.display import display, HTML

used IPython.core to display a image

In [ ]:
display(HTML('<h1>Hello, world!</h1>'))

displayed hello world

In [ ]:
def coin():
  return np.random.randint(2)

defined coin as np.random.randint(2)

In [ ]:
coin()

1

used the function

In [ ]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))

insert picture of heads on a quarter

In [ ]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

inserted image of heads and tails to display them when we use flip coin

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

use this to insert the image when we use it

In [ ]:
show_img(heads)

use show_img to show heads img


In [ ]:
show_img(tails)

use show_img to show tails img


In [ ]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

use def flip coin to show img of heads if > 0.5 
show img of tails if < 0.5

In [ ]:
flip_coin()

flipped coin and got heads

In [ ]:
for i in range(5):
    flip_coin()

flipped coin 5 times to test out coding

In [ ]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [ ]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

inserted shuffle feauture
gave range of (len(x)-1,0,-1):
inserted a random number 


In [ ]:
a = np.arange(52)

created a arrange of 52 
(the amount of cards in a deck)

In [ ]:
shuffle(a)

array([49, 37,  1, 13, 15, 10,  8,  4, 39, 31, 23, 25, 22, 47,  6, 19, 11,
       17, 50, 43, 32, 12, 30, 36, 34, 44, 40, 42,  2,  9, 33, 24, 35,  3,
       41, 46, 48, 16, 27, 28,  7, 20, 18, 45, 14, 38, 29,  5, 26, 51,  0,
       21])

used shuffle "a" to shuffle the numbers randomly

In [ ]:
np.random.permutation(52)

array([42,  1, 41, 31,  9,  8, 45,  4, 39, 25, 37,  3, 13, 32,  2, 50,  5,
       34,  7, 26, 43, 23, 10, 14, 30, 29, 21, 35, 11, 36, 47, 16, 28, 22,
       27, 17, 15, 19, 33, 24, 38, 44,  0, 48, 18, 40, 46, 12, 49, 51, 20,
        6])

used permutation to amke sure the numbers are arranged in various amounts of ways

### Speed Test

In [ ]:
%%timeit
shuffle(a)

192 µs ± 13.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


used timeit to run a test of loops on the shuffle array we made

In [ ]:
%%timeit
np.random.permutation(52)

3.48 µs ± 263 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


used timeit to run a test of loops on the permutation array we made

In [ ]:
import numpy as np

In [ ]:
np.random.permutation(52)

array([ 0, 32, 18,  9, 44, 47, 31, 22, 34, 12, 42, 40,  7, 24, 45, 51, 21,
       25, 15, 29, 14,  3, 38, 27, 17,  8, 36, 39, 43,  6, 33, 37, 23, 35,
       26,  2, 41, 48, 30, 28, 20, 11,  5, 10, 49, 46,  1, 13, 16, 50,  4,
       19])

In [ ]:
cards = np.random.permutation(52)

inserted cards as the permutation array we created 

In [ ]:
cards

array([35,  4, 13,  5, 31,  0, 21, 37, 29, 26, 25,  7, 39, 17,  3, 20,  1,
       38, 34, 18, 50, 44,  8, 51, 16, 48,  2, 46, 30, 23, 28, 11, 10, 12,
       22, 36, 49,  6, 24, 19, 42, 15, 27, 40, 33, 45, 41, 14, 43, 32,  9,
       47])

inserted cards

In [ ]:
cards[0]

35

In [ ]:
cards[1]

4

In [ ]:
cards[2]

13

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

inserted images of a deck of cards

In [ ]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

reshaped our array to seperate them into groups matching the images
this is used to give the images a value

In [ ]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

shortened the array into shorter numbers to simplify

In [ ]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

assigned each row their own number to assign a suit to each

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

inserted the suits and names of each card type to easily place them on our array

In [ ]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

gave the cuit card numbers from //13 
and gave card numbers through %13

In [ ]:
card_name(0)

'Ace of Clubs'

tested our numbers out

In [ ]:
card_name(51)

'King of Diamonds'

double checked

In [ ]:
cards = np.random.permutation(52)

In [ ]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

inserted the top of deck as card_name(cards[0])
inserted the second card in deck as [1]
inserted last card in deck as [-1]

In [ ]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Three of Clubs', 'Queen of Hearts', 'Six of Hearts')

tested our scale

In [ ]:
for i in range(5):
    print(card_name(cards[i]))

Three of Clubs
Queen of Hearts
Queen of Spades
Seven of Spades
Three of Diamonds


printed a range of 5 cards

In [ ]:
for i in range(15):
    print(card_name(cards[i]))

Three of Clubs
Queen of Hearts
Queen of Spades
Seven of Spades
Three of Diamonds
Four of Clubs
King of Diamonds
Seven of Diamonds
Three of Spades
Two of Spades
Six of Diamonds
Eight of Clubs
Three of Hearts
Four of Diamonds
Ace of Spades


printed a range of 15 random cards

https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

inserted card url head

inserted card url tail

In [ ]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

inserted suits and card  giving them all calues

In [ ]:
i = np.random.randint(4)
j = np.random.randint(13)

gave i and j values of random numbers

i = (4)

j = (13)

In [ ]:
i,j

(1, 1)

INSERTed i and j to get a pair

In [ ]:
suit[i]

'p'

In [ ]:
card[j]

'2'

In [ ]:
from IPython.core.display import display, HTML

inserted the the display from html function

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [ ]:
img = card_url_head + suit[i] + card[j] + card_url_tail

made a img valued as card head + suit + card + card url rail

In [ ]:
show_img(img)

showed img

In [ ]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

defined the cards

In [ ]:
card_image(3)

'k4'

searched for card image (3)

In [ ]:
img = card_url_head + card_image(3) + card_url_tail

In [ ]:
show_img(img)

In [ ]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)

searched all cards in order